### PR TITLE
Revamp discover screen and fix home screen constraints

### LINKED ISSUE #452: Create Custom Navigation Bar for playlist views
**Designs**
Refer to Zeplin designs in our project.

### PR DESCRIPTION
**Pull request by jaewonsim**
Resolves #452 and #456 
- Fix constraints on home screen
- Add a new discover view controller with collection view

### CODE REVIEW

File: Recast/Discover/DiscoverCollectionViewCell.swift [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+        super.init(frame: frame)
+
+        contentView.backgroundColor = .black
+
+        faceImageView = UIImageView()
+        faceImageView.contentMode = .scaleAspectFit
+        contentView.addSubview(faceImageView)
+
+        durationDescriptionLabel = UILabel()
+        durationDescriptionLabel.font = UIFont.systemFont(ofSize: 20, weight: .semibold)
```
Comment (mindylou) [inline Recast/Discover/DiscoverCollectionViewCell.swift]:
```suggestion
        durationDescriptionLabel.font = .systemFont(ofSize: 20, weight: .semibold)
```
this should work

File: Recast/Discover/DiscoverCollectionViewCell.swift [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+        durationDescriptionLabel.textColor = .white
+        durationDescriptionLabel.textAlignment = .center
+        contentView.addSubview(durationDescriptionLabel)
+
+        minutesLabel = UILabel()
+        minutesLabel.font = UIFont.systemFont(ofSize: 18)
```
Comment (mindylou) [inline Recast/Discover/DiscoverCollectionViewCell.swift]:
```suggestion
        minutesLabel.font = .systemFont(ofSize: 18)
```

File: Recast/Discover/DiscoverViewController.swift [hunk 3]
```diff
@@ -2,40 +2,135 @@
 //  DiscoverViewController.swift
 //  Recast
 //
-//  Created by Jack Thompson on 9/19/18.
+//  Created by Jaewon Sim on 11/7/18.
```
Comment (mindylou) [inline Recast/Discover/DiscoverViewController.swift:5]: 😮

File: Recast/Discover/DiscoverViewController.swift [hunk 4]
```diff
@@ -2,40 +2,135 @@
...
+    let durationSelectorReuse = "durationSelectorReuse"
 
+    // MARK: - Lifecycle
     override func viewDidLoad() {
         super.viewDidLoad()
+        view.backgroundColor = .black
+
+        titleLabel = UILabel()
+        titleLabel.text = "How much time do you have right now?"
+        titleLabel.font = UIFont.systemFont(ofSize: 24, weight: .medium)
```
Comment (mindylou) [inline Recast/Discover/DiscoverViewController.swift]:
```suggestion
        titleLabel.font = .systemFont(ofSize: 24, weight: .medium)
```

File: Recast/Discover/DiscoverViewController.swift [hunk 5]
```diff
@@ -2,40 +2,135 @@
...
+        // MARK: Layout constants
+        let searchBarTitleLabelHorizontalSpacing: CGFloat = 10.3
+        let titleLabelCollectionViewHorizontalSpacing: CGFloat = 28.7
+        let collectionViewPageControlVerticalSpacing: CGFloat = 12
+        let titleLabelSideInset: CGFloat = 33
+        let collectionViewHeight: CGFloat = 450
+
+        titleLabel.snp.makeConstraints { make in
+            make.top.equalTo(view.safeAreaLayoutGuide.snp.top).offset(searchBarTitleLabelHorizontalSpacing)
+            make.left.right.equalTo(view.safeAreaLayoutGuide).inset(titleLabelSideInset)
```
Comment (mindylou) [inline Recast/Discover/DiscoverViewController.swift]:
```suggestion
            make.leading.trailing.equalTo(view.safeAreaLayoutGuide).inset(titleLabelSideInset)
```

File: Recast/Discover/DiscoverViewController.swift [hunk 6]
```diff
@@ -2,40 +2,135 @@
...
         }
+
+        durationSelectorCollectionView.snp.makeConstraints { make in
+            make.top.equalTo(titleLabel.snp.bottom).offset(titleLabelCollectionViewHorizontalSpacing)
+            make.height.equalTo(collectionViewHeight)
+            make.left.right.equalToSuperview()
```
Comment (mindylou) [inline Recast/Discover/DiscoverViewController.swift]:
```suggestion
            make.leading.trailing.equalToSuperview()
```

**Review by mindylou — COMMENTED** [review]
once these are fixed i'll approve!

**Review by mindylou — DISMISSED** [review]
