### PR TITLE
Implement feed cell protocol and fix feed performance

### LINKED ISSUE #194: Fix feed cells

### PR DESCRIPTION
**Pull request by dantheli**
lmk if you still get constraint errors, i didn't really address that through this refactor but we'll see

This fixes feed performance by creating a protocol that two different feed cells conform to. Observe that despite there being two different types of cells, cellForRowAtIndexPath consists of just two lines of code

Fixes #194

### CODE REVIEW

**Comment by dantheli** [comment]
Unfinished, will reopen later

File: Podcast/FeedElementTableViewCell.swift [hunk 1]
```diff
@@ -10,123 +10,64 @@ import UIKit
...
-    func feedElementTableViewCellDidPressEpisodeSubjectViewPlayPauseButton(feedElementTableViewCell: FeedElementTableViewCell, episodeSubjectView: EpisodeSubjectView)
-    func feedElementTableViewCellDidPressEpisodeSubjectViewBookmarkButton(feedElementTableViewCell: FeedElementTableViewCell, episodeSubjectView: EpisodeSubjectView)
-    func feedElementTableViewCellDidPressEpisodeSubjectViewTagButton(feedElementTableViewCell: FeedElementTableViewCell, episodeSubjectView: EpisodeSubjectView, index: Int)
-    func feedElementTableViewCellDidPressEpisodeSubjectViewRecommendedButton(feedElementTableViewCell: FeedElementTableViewCell, episodeSubjectView: EpisodeSubjectView)
-    func feedElementTableViewCellDidPressSupplierViewFeedControlButton(feedElementTableViewCell: FeedElementTableViewCell, supplierView: UserSeriesSupplierView)
-    func feedElementTableViewCellDidPressSeriesSubjectViewSubscribeButton(feedElementTableViewCell: FeedElementTableViewCell, seriesSubjectView: SeriesSubjectView)
+    func didPressMoreButton(for episodeSubjectView: EpisodeSubjectView, in cell: UITableViewCell)
```
Comment (doctor3w) [inline Podcast/FeedElementTableViewCell.swift:13]: Love this name formatting. Pure orgasmic swift.

File: Podcast/FeedElementTableViewCell.swift [hunk 2]
```diff
@@ -10,123 +10,64 @@ import UIKit
...
+extension UITableView {
+    fileprivate var feedElementTableViewCells: [(UITableViewCell & FeedElementTableViewCell).Type] {
+        return [FeedEpisodeTableViewCell.self, FeedSeriesTableViewCell.self]
     }
-    
-    func episodeSubjectViewDidPressMoreActionsButton(episodeSubjectView: EpisodeSubjectView) {
-        delegate?.feedElementTableViewCellDidPressEpisodeSubjectViewMoreButton(feedElementTableViewCell: self, episodeSubjectView: episodeSubjectView)
+
+    func registerFeedElementTableViewCells() {
+        feedElementTableViewCells.forEach { register($0, forCellReuseIdentifier: $0.identifier) }
```
Comment (doctor3w) [inline Podcast/FeedElementTableViewCell.swift:64]: Nice

File: Podcast/UserSeriesSupplierView.swift [hunk 3]
```diff
@@ -109,6 +110,8 @@ class UserSeriesSupplierView: FeedElementSupplierView {
     }
     
     func setupWithUsers(users: [User], feedContext: FeedContext) {
+        contextImages.arrangedSubviews.forEach { $0.removeFromSuperview() }
```
Comment (doctor3w) [inline Podcast/UserSeriesSupplierView.swift:113]: Nice

**Review by doctor3w — APPROVED** [review]
Looks great

File: Podcast/FeedViewController.swift [hunk 4]
```diff
@@ -85,6 +86,9 @@ class FeedViewController: ViewController, UITableViewDelegate, UITableViewDataSo
         refreshControl.endRefreshing()
     }
 
+}
+
+extension FeedViewController: UITableViewDataSource, UITableViewDelegate {
```
Comment (natashaarmbrust) [inline Podcast/FeedViewController.swift]: are we just putting this as an extension for clarity sake or is there a specific reason?

File: Podcast/FeedElementTableViewCell.swift [hunk 5]
```diff
@@ -10,123 +10,64 @@ import UIKit
...
-    
-    func episodeSubjectViewDidPressBookmarkButton(episodeSubjectView: EpisodeSubjectView) {
-        delegate?.feedElementTableViewCellDidPressEpisodeSubjectViewBookmarkButton(feedElementTableViewCell: self, episodeSubjectView: episodeSubjectView)
-    }
-    
-    func episodeSubjectViewDidPressTagButton(episodeSubjectView: EpisodeSubjectView, index: Int) {
-        delegate?.feedElementTableViewCellDidPressEpisodeSubjectViewTagButton(feedElementTableViewCell: self, episodeSubjectView: episodeSubjectView, index: index)
+}
+
+extension UITableView {
```
Comment (natashaarmbrust) [inline Podcast/FeedElementTableViewCell.swift:58]: can we have multiple UITableView extensions floating around? If not, we might want to abstract this out to a UITableView+ file just so all our extensions are in the same place

**Review by natashaarmbrust — COMMENTED** [review]
Beautiful code dan! Only two comments. Reply (make changes if necessary) and merge in.

File: Podcast/FeedElement.swift [hunk 6]
```diff
@@ -35,6 +35,17 @@ enum FeedContext {
...
     }
+
+    var cellType: FeedElementTableViewCell.Type {
+        switch self {
+        case .followingRecommendation:
+            return FeedEpisodeTableViewCell.self
+        case .followingSubscription:
+            return FeedEpisodeTableViewCell.self
+        case .newlyReleasedEpisode:
+            return FeedEpisodeTableViewCell.self
```
Comment (mindylou) [inline Podcast/FeedElement.swift]: just curious, why are all three of these cases returning the same thing?

File: Podcast/FeedElementTableViewCell.swift (hunk 1 above)
Comment (mindylou) [reply Podcast/FeedElementTableViewCell.swift:13]: ~ swifty ~

**Review by mindylou — APPROVED** [review]
lgtm!

File: Podcast/FeedElement.swift (hunk 6 above)
Comment (dantheli) [reply Podcast/FeedElement.swift]: And this is why we have code review!! Thanks for catching this

File: Podcast/FeedElementTableViewCell.swift (hunk 5 above)
Comment (dantheli) [reply Podcast/FeedElementTableViewCell.swift:58]: Personally I like having them in relevant places since potentially we could end up with a huge file of extensions with no organization of where each one is or what each one does.
But honestly I don't mind. If you want to you can take it out when we get more extensions later.

Comment (natashaarmbrust) [reply Podcast/FeedElementTableViewCell.swift:58]: It's fine let's keep it in here for rn.

File: Podcast/FeedViewController.swift (hunk 4 above)
Comment (dantheli) [reply Podcast/FeedViewController.swift]: Well clarity, but also the FeedViewController declaration line was getting too long

Comment (natashaarmbrust) [reply Podcast/FeedViewController.swift]: lol .. ok with me but make a comment that its for clarities sake so that prior iOS devs don't get confused that there was a reason
