### PR TITLE
Natasha/v3 fixes

### LINKED ISSUE #410: Saved for later tableview insets not updating
They don't update upon first pressing play + collapsing to mini player (can't see last table view cell)

img_1554

### PR DESCRIPTION
**Pull request by natashaarmbrust**
- Fixes #410 and #409

### CODE REVIEW

File: Podcast/TopSearchResultsViewController.swift [hunk 1]
```diff
@@ -68,6 +68,8 @@ class TopSearchResultsViewController: ViewController, UITableViewDataSource, UIT
         }
         
         searchResultsTableView.layoutIfNeeded()
+
+        mainScrollView = searchResultsTableView
```
Comment (mindylou) [inline Podcast/TopSearchResultsViewController.swift:72]: i'm getting large titles from search to episode detail (not sure if this is related) 

image

**Review by mindylou — APPROVED** [review]
LGTM! just one other small bug i found
