### PR TITLE
Jack/fixes

### LINKED ISSUE #347: iPhone X player padding
action sheet icon too low on iphone x in full player :(
18727e71-5141-4ad5-8986-3478b5202269

### PR DESCRIPTION
**Pull request by jackthmp**
Fixes #347, #344, #336, #331

### CODE REVIEW

File: Podcast/User.swift [hunk 1]
```diff
@@ -121,15 +121,18 @@ class User: NSObject {
...
     func changeUsername(username: String, success: (() -> ())? = nil, failure: (() -> ())? = nil) {
-        let changeUsernameEndpointRequest = ChangeUsernameEndpointRequest(username: username)
-        changeUsernameEndpointRequest.success = { (endpointRequest: EndpointRequest) in
-            self.username = username
-            success?()
-        }
+        if username.contains(" ") || username == "" { failure?() }
+        else {
+            let changeUsernameEndpointRequest = ChangeUsernameEndpointRequest(username: username)
+            changeUsernameEndpointRequest.success = { (endpointRequest: EndpointRequest) in
```
Comment (natashaarmbrust) [inline Podcast/User.swift]: `_ in ....` instead of `(endpointRequest: EndpointRequest) in .. `

File: Podcast/User.swift [hunk 2]
```diff
@@ -121,15 +121,18 @@ class User: NSObject {
...
+                self.username = username
+                success?()
+            }
 
-        changeUsernameEndpointRequest.failure = { (endpointRequest: EndpointRequest) in
-            failure?()
+            changeUsernameEndpointRequest.failure = { (endpointRequest: EndpointRequest) in
```
Comment (natashaarmbrust) [inline Podcast/User.swift]: same here

**Review by natashaarmbrust — APPROVED** [review]
LGTM
